# required configuration options
name: Fusion (cd1zz-dev)
version: 2025.10.0
slug: ha_fusion
description: A modern, easy-to-use and performant custom Home Assistant dashboard (Testing Fork - Item Visibility Template - v1c6ddc8)
arch:
  - aarch64
  - amd64
  - armv7

# disable the docker default system init
init: false

# homepage of the add-on
url: https://github.com/cd1zz/addon-ha-fusion

# icon for the menu panel integration
panel_icon: mdi:atom

# allow non-administration users
panel_admin: false

# security profile
apparmor: true

# ingress feature for the add-on
ingress: true
ingress_stream: true

# enable api to get host port
hassio_api: true

# port to expose, null defaults to disabled
ports:
  8099/tcp: null

# build arguments to force cache invalidation
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.20
  amd64: ghcr.io/home-assistant/amd64-base:3.20
  armv7: ghcr.io/home-assistant/armv7-base:3.20
args:
  BUILD_VERSION: "2025.10.0"

# docker hub - commented out for local build from repository
# image: matt8707/addon-ha-fusion-{arch}
