# DISABLED: This workflow publishes pre-built Docker images to Docker Hub.
# Since this fork builds from source (not publishing images), this workflow is disabled.
# If you want to publish your own images, uncomment and update the docker-hub username.

# name: "Publish"
#
# on:
#   workflow_dispatch:
#   push:
#     branches: ["main"]
#
# jobs:
#   publish:
#     name: Publish
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout the repository
#         uses: actions/checkout@v4
#       - name: Login to DockerHub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
#       - name: Publish
#         uses: home-assistant/builder@master
#         with:
#           args: |
#             --all \
#             --target /data \
#             --docker-hub cd1zz
